apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "finops-moving-window-microservice.fullname" . }}
  labels:
  {{- include "finops-moving-window-microservice.labels" . | nindent 4 }}
data:
  RESOURCE_TREE_HANDLER_API_PORT: "{{ .Values.service.port }}"
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}